### ISSUE TITLE
Move repository to koopjs Org

### ISSUE THREAD

**Issue by slibby** [koopjs/koop-provider-mongo#1]
Expected to find this under github.com/koopjs -- let's move it there unless there's a reason not to. cc @ngoldman

**Comment by chelm** [comment]
well the reason was only due to it being neglected and I thought I'd move once I had a chance to spruce it up.

**Comment by chelm** [comment]
cc @slibby

**Comment by ungoldman** [comment]
:+1: spruce and move as time allows :hourglass_flowing_sand:

**Comment by ungoldman** [comment]
hey you guys, wanna move it? kill it? trying to reduce my open issue count to sub-nightmare levels

**Comment by chelm** [comment]
We can let @dmfenton decide. He is the koop keymaster now.

**Comment by dmfenton** [comment]
Cool with me

**Comment by ungoldman** [comment]
We did it 🎉

Hope y'all are doing well by the way

**Comment by chelm** [comment]
Doing fantastic, @ungoldman, Hope PDX is still great -say hi to @JerrySievert for me if you ever see him

**Comment by ungoldman** [comment]
Will do, might see him this Sunday for the geotrigger wake ([RIP](https://developers.arcgis.com/geotrigger-service/))

PDX is still great!
